version: "1"
rules:
  - base: master
    upstream: blender:master
    mergeMethod: merge
  - base: blender-v3.3-release
    upstream: blender-v3.3-release
    mergeMethod: hardreset
  - base: blender-v3.4-release
    upstream: blender-v3.4-release
    mergeMethod: hardreset
  - base: blender-v2.93-release
    upstream: blender-v2.93-release
    mergeMethod: hardreset
